#!/system/bin/sh
#
# Print startup info
#
L="log -p i -t slim"

$L "  ______       ___             ___    _____   "
$L " /      \  ___/   \           /   \  /     \  "
$L "/        \/   \___/____   ____|   |  |   0  | "
$L "|    \___/|   |___/    \_/    |   |  |      | "
$L "\        \|   |   |           |   |  |    _/  "
$L " \___/    |   |   |   |   |   |   |__|   |    "
$L " /        |   |   |   |   |   |      |   |    "
$L " \_______/\___^___^___^___^___^______^___/    "
$L "Welcome to Android `getprop ro.build.version.release` / SlimLP `getprop ro.slim.version`";
